
/*------------------------------------------------------------------------
    File        : IReadResponse
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Mon Jul 06 09:03:57 CEST 2020
    Notes       : 
  ----------------------------------------------------------------------*/


interface bfvlib.net.IReadResponse:  
    
    method public void ProcessResponse(responseText as longchar).
      
end interface.