
/*------------------------------------------------------------------------
    File        : IOauth2Token
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Thu Sep 24 08:55:39 CEST 2020
    Notes       : 
  ----------------------------------------------------------------------*/


interface bfvlib.auth.oauth2.IOauth2Token:  
    
    define public property Token as character no-undo get.
      
end interface.