
/*------------------------------------------------------------------------
    File        : IOauth2Login
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Thu Sep 24 08:34:06 CEST 2020
    Notes       : 
  ----------------------------------------------------------------------*/


interface bfvlib.auth.oauth2.IOauth2Login:  
    
    method public logical Login().
    
end interface.