
/*------------------------------------------------------------------------
    File        : HttpVerbs
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Fri May 08 19:14:21 CEST 2020
    Notes       : 
  ----------------------------------------------------------------------*/

enum bfvlib.mock.HttpVerbs flags :  

    define enum GET = 1
                POST = 2
                PUT = 4
                DELETE = 8
                PATCH = 16.

end enum.